env:
  es6: true
  shared-node-browser: true

extends: 'eslint:recommended'

parserOptions:
  ecmaFeatures:
    impliedStrict: true
  ecmaVersion: 2017
  sourceType: module

rules:
  brace-style:
    - error
    - allman
    -
      allowSingleLine: true
  curly:
    - error
  eqeqeq:
    - error
    - smart
  indent:
    - error
    - 4
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-console:
    - off
  no-var:
    - error
  no-trailing-spaces:
    - error
  prefer-const:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - never